import images from "./images/images";

const Products = [
  {
    name: "Armorized Deadpool",
    price: 420,
    universe: "marvel",
    affiliation: "xmen",
    hero: "deadpool",
    image: images.marvel.armorized_deadpool,
    count: 0,
  },
  {
    name: "Captain America",
    price: 350,
    universe: "marvel",
    affiliation: "avengers",
    hero: "captainAmerica",
    image: images.marvel.captain_america,
    count: 0,
  },
  {
    name: "Deadpool",
    price: 250,
    universe: "marvel",
    affiliation: "xmen",
    hero: "deadpool",
    image: images.marvel.deadpool,
    count: 0,
  },
  {
    name: "Gambit Deluxe",
    price: 300,
    universe: "marvel",
    affiliation: "xmen",
    hero: "gambit",
    image: images.marvel.gambit_deluxe,
    count: 0,
  },
  {
    name: "Hulk Vs Hulkbuster",
    price: 750,
    universe: "marvel",
    affiliation: "avengers",
    hero: "hulk",
    image: images.marvel.hulk_vs_hulkbuster,
    count: 0,
  },
  {
    name: "Iron Man Mark XLiii",
    price: 520,
    universe: "marvel",
    affiliation: "avengers",
    hero: "ironMan",
    image: images.marvel.iron_main_mark_xlii,
    count: 0,
  },
  {
    name: "Iron Man Neon Tech 40",
    price: 630,
    universe: "marvel",
    affiliation: "avengers",
    hero: "ironMan",
    image: images.marvel.iron_man_neon_tech_40,
    count: 0,
  },
  {
    name: "Quicksilver",
    price: 350,
    universe: "marvel",
    affiliation: "xmen",
    hero: "quicksilver",
    image: images.marvel.quicksilver,
    count: 0,
  },
  {
    name: "Spider Man",
    price: 300,
    universe: "marvel",
    affiliation: "avengers",
    hero: "spiderman",
    image: images.marvel.spider_man,
    count: 0,
  },
  {
    name: "Spider Man Deluxe Version",
    price: 850,
    universe: "marvel",
    affiliation: "avengers",
    hero: "spiderman",
    image: images.marvel.spider_man_deluxe_version_special_edition,
    count: 0,
  },
  {
    name: "Spider Man Negative Zone Suit",
    price: 400,
    universe: "marvel",
    affiliation: "avengers",
    hero: "spiderman",
    image: images.marvel.spider_man_negative_zone_suit,
    count: 0,
  },
  {
    name: "Thor Endgame",
    price: 350,
    universe: "marvel",
    affiliation: "avengers",
    hero: "thor",
    image: images.marvel.thor_sixth_scale_figure,
    count: 0,
  },
  {
    name: "Venomized Groot",
    price: 500,
    universe: "marvel",
    affiliation: "guardians",
    hero: "groot",
    image: images.marvel.venomized_groot,
    count: 0,
  },
  {
    name: "Wolverine",
    price: 300,
    universe: "marvel",
    affiliation: "xmen",
    hero: "wolverine",
    image: images.marvel.wolverine,
    count: 0,
  },
];

export default Products;
