import images from "./images/images";

const Products = [
  {
    name: "Armorized Deadpool",
    price: 420,
    universe: "marvel",
    affiliation: "xmen",
    hero: "deadpool",
    image: images.marvel.armorized_deadpool,
    count: 0,
  },
  {
    name: "Captain America",
    price: 350,
    universe: "marvel",
    affiliation: "avengers",
    hero: "captainAmerica",
    image: images.marvel.captain_america,
    count: 0,
  },
  {
    name: "Deadpool",
    price: 250,
    universe: "marvel",
    affiliation: "xmen",
    hero: "deadpool",
    image: images.marvel.deadpool,
    count: 0,
  },
  {
    name: "Gambit Deluxe",
    price: 300,
    universe: "marvel",
    affiliation: "xmen",
    hero: "gambit",
    image: images.marvel.gambit_deluxe,
    count: 0,
  },
  {
    name: "Hulk Vs Hulkbuster",
    price: 750,
    universe: "marvel",
    affiliation: "avengers",
    hero: "hulk",
    image: images.marvel.hulk_vs_hulkbuster,
    count: 0,
  },
  {
    name: "Iron Man Mark XLiii",
    price: 520,
    universe: "marvel",
    affiliation: "avengers",
    hero: "ironMan",
    image: images.marvel.iron_main_mark_xlii,
    count: 0,
  },
  {
    name: "Iron Man Neon Tech 40",
    price: 630,
    universe: "marvel",
    affiliation: "avengers",
    hero: "ironMan",
    image: images.marvel.iron_man_neon_tech_40,
    count: 0,
  },
  {
    name: "Quicksilver",
    price: 350,
    universe: "marvel",
    affiliation: "xmen",
    hero: "quicksilver",
    image: images.marvel.quicksilver,
    count: 0,
  },
  {
    name: "Spider Man",
    price: 300,
    universe: "marvel",
    affiliation: "avengers",
    hero: "spiderman",
    image: images.marvel.spider_man,
    count: 0,
  },
  {
    name: "Spider Man Deluxe Version",
    price: 850,
    universe: "marvel",
    affiliation: "avengers",
    hero: "spiderman",
    image: images.marvel.spider_man_deluxe_version_special_edition,
    count: 0,
  },
  {
    name: "Spider Man Negative Zone Suit",
    price: 400,
    universe: "marvel",
    affiliation: "avengers",
    hero: "spiderman",
    image: images.marvel.spider_man_negative_zone_suit,
    count: 0,
  },
  {
    name: "Thor Endgame",
    price: 350,
    universe: "marvel",
    affiliation: "avengers",
    hero: "thor",
    image: images.marvel.thor_sixth_scale_figure,
    count: 0,
  },
  {
    name: "Venomized Groot",
    price: 500,
    universe: "marvel",
    affiliation: "guardians",
    hero: "groot",
    image: images.marvel.venomized_groot,
    count: 0,
  },
  {
    name: "Wolverine",
    price: 300,
    universe: "marvel",
    affiliation: "xmen",
    hero: "wolverine",
    image: images.marvel.wolverine,
    count: 0,
  },
  {
    name: "Batman",
    price: 290,
    universe: "dc",
    affiliation: "heroes",
    hero: "batman",
    image: images.dc.batman,
    count: 0,
  },
  {
    name: "Golden Armour Wonder Woman (Deluxe)",
    price: 360,
    universe: "dc",
    affiliation: "heroes",
    hero: "wonderwoman",
    image: images.dc.golden_armour_wonder_woman,
    count: 0,
  },
  {
    name: "Superman Black Suit",
    price: 160,
    universe: "dc",
    affiliation: "heroes",
    hero: "superman",
    image: images.dc.superman_black_suite,
    count: 0,
  },
  {
    name: "Catwoman",
    price: 590,
    universe: "dc",
    affiliation: "heroes",
    hero: "catwoman",
    image: images.dc.catwoman,
    count: 0,
  },
  {
    name: "The Joker",
    price: 330,
    universe: "dc",
    affiliation: "villain",
    hero: "joker",
    image: images.dc.the_joker,
    count: 0,
  },
  {
    name: "Catwoman Laying Dowm",
    price: 590,
    universe: "dc",
    affiliation: "heroes",
    hero: "catwoman",
    image: images.dc.catwoman_laying_down,
    count: 0,
  },
  {
    name: "Superman: Call to Action",
    price: 600,
    universe: "dc",
    affiliation: "heroes",
    hero: "superman",
    image: images.dc.superman_call_to_action,
    count: 0,
  },
  {
    name: "Batman vs The Joker",
    price: 350,
    universe: "dc",
    affiliation: "heroes",
    hero: "batman",
    image: images.dc.batman_vs_the_joker,
    count: 0,
  },
  {
    name: "Green Lantern",
    price: 275,
    universe: "dc",
    affiliation: "heroes",
    hero: "greenlantern",
    image: images.dc.green_lantern,
    count: 0,
  },
  {
    name: "Black Canary",
    price: 555,
    universe: "dc",
    affiliation: "heroes",
    hero: "blackcanary",
    image: images.dc.black_canary,
    count: 0,
  },
  {
    name: "Harley Quinn (Caution Tape Jacket Version)",
    price: 281,
    universe: "dc",
    affiliation: "villain",
    hero: "harleyquinn",
    image: images.dc.harley_quinn_caution_tape,
    count: 0,
  },
  {
    name: "Batgirl",
    price: 243,
    universe: "dc",
    affiliation: "heroes",
    hero: "batgirl",
    image: images.dc.batgirl,
    count: 0,
  },
  {
    name: "Batwoman Who Laughs",
    price: 600,
    universe: "dc",
    affiliation: "heroes",
    hero: "batman",
    image: images.dc.batman_who_laughs,
    count: 0,
  },
  {
    name: "Power Girl",
    price: 585,
    universe: "dc",
    affiliation: "heroes",
    hero: "powergirl",
    image: images.dc.power_girl,
    count: 0,
  },
  {
    name: "The Flash",
    price: 250,
    universe: "dc",
    affiliation: "heroes",
    hero: "flash",
    image: images.dc.the_flash_sixth_scale,
    count: 0,
  },
  {
    name: "Harley Quinn",
    price: 900,
    universe: "dc",
    affiliation: "villain",
    hero: "harleyquinn",
    image: images.dc.harley_quinn,
    count: 0,
  },
  {
    name: "Darkseid",
    price: 655,
    universe: "dc",
    affiliation: "villain",
    hero: "darkseid",
    image: images.dc.darkseid,
    count: 0,
  },
  {
    name: "Catwoman Batman Returns",
    price: 140,
    universe: "dc",
    affiliation: "heroes",
    hero: "batgirl",
    image: images.dc.catwoman_batman_returns,
    count: 0,
  },
  {
    name: "Batman Batcave Version",
    price: 149,
    universe: "dc",
    affiliation: "heroes",
    hero: "batman",
    image: images.dc.batman_batcave_version,
    count: 0,
  },
  {
    name: "Catwoman Premium Format",
    price: 565,
    universe: "dc",
    affiliation: "heroes",
    hero: "catwoman",
    image: images.dc.catwoman_premium_format,
    count: 0,
  },
];

export default Products;
